In [6]:
import torch
from torch.autograd import Variable
import torch.optim as optim

In [7]:
# Define the linear model function
def linear_model(x, W, b):
    print(x)
    o = torch.mul(x, W) + b
    return o

In [8]:
# Training data and targets
data = torch.arange(1, 20001).reshape(20000, 1).float()
targets = (torch.arange(1, 20001) * 200).reshape(20000, 1).float()





In [11]:
# Initialize weights and bias
W = Variable(torch.tensor([190.]), requires_grad=True)
b = Variable(torch.tensor(1.), requires_grad=True)

# Optimizer
optimizer = optim.Adam([W])

# Training loop
for sample, target in zip(data, targets):
    optimizer.zero_grad(set_to_none=True)  # Clear the gradients
    output = linear_model(sample, W, b)  # Forward pass
    loss = (output - target) ** 2  # Compute loss
    loss.backward(torch.ones_like(loss))  # Backward pass (gradient computation)
    optimizer.step()  # Update weights


tensor([1.])
tensor([2.])
tensor([3.])
tensor([4.])
tensor([5.])
tensor([6.])
tensor([7.])
tensor([8.])
tensor([9.])
tensor([10.])
tensor([11.])
tensor([12.])
tensor([13.])
tensor([14.])
tensor([15.])
tensor([16.])
tensor([17.])
tensor([18.])
tensor([19.])
tensor([20.])
tensor([21.])
tensor([22.])
tensor([23.])
tensor([24.])
tensor([25.])
tensor([26.])
tensor([27.])
tensor([28.])
tensor([29.])
tensor([30.])
tensor([31.])
tensor([32.])
tensor([33.])
tensor([34.])
tensor([35.])
tensor([36.])
tensor([37.])
tensor([38.])
tensor([39.])
tensor([40.])
tensor([41.])
tensor([42.])
tensor([43.])
tensor([44.])
tensor([45.])
tensor([46.])
tensor([47.])
tensor([48.])
tensor([49.])
tensor([50.])
tensor([51.])
tensor([52.])
tensor([53.])
tensor([54.])
tensor([55.])
tensor([56.])
tensor([57.])
tensor([58.])
tensor([59.])
tensor([60.])
tensor([61.])
tensor([62.])
tensor([63.])
tensor([64.])
tensor([65.])
tensor([66.])
tensor([67.])
tensor([68.])
tensor([69.])
tensor([70.])
tensor([71.])
tensor([72.])
t

In [12]:

# Test the trained model with a sample input
test_sample = torch.tensor([-100]).float()  # Define a test sample
test_output = linear_model(test_sample, W, b)  # Forward pass with the test sample
print("Test input:", test_sample)
print("Model output for test input:", test_output)

tensor([-100.])
Test input: tensor([-100.])
Model output for test input: tensor([-19998.9961], grad_fn=<AddBackward0>)
